# Generated by Django 3.0.4 on 2020-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=255)),
                ('price', models.IntegerField(verbose_name='price')),
                ('offer', models.BooleanField(default=False, verbose_name='offer')),
            ],
        ),
    ]
